### ISSUE TITLE
Encoding Problem in Properties

### ISSUE THREAD

**Issue by akurone** [otykier/TabularEditor#169]
hi,
first of all thanks for this great tool!
with the versions after 2.7.6630.12408 release there is problem when using Turkish code page (mostly win-1254):
the "ı" and "i" are (small letter "I" with and without a dot) are different letters in Turkish. For example in a db connection the property "impersonationMode" has the value of "ımpersonateServiceAccount" (saved with the mentioned version). Saving the same model with a newer version makes this property "impersonateServiceAccount" and SSAS server complains that there is no valid value for this property with this name.. same for data types: "ınt64"/"int64"

![untitled](https://user-images.githubusercontent.com/841676/41862056-99bfd95a-78ab-11e8-8ec1-b756fa73c7b7.png)

**Comment by otykier** [comment]
Thanks for reporting this. It's an interesting issue. To the best of my knowledge, nothing was changed in the Tabular Editor source code that would affect the encoding of properties. So my best guess is, that this is an issue in the newer versions of the AMO/TOM API (newer versions of Tabular Editor uses AMO/TOM API v. 15.x, where as previously it used 14.x).

A couple of questions:

- Does this only happen after you set the value of "impersonationMode" through the Tabular Editor UI?
- Does this happen to all strings in the Model.bim file, or only certain properties, like "impersonationMode"? For example, if you have a column where the dataType property is "string", do you observe the same behaviour?
- Do you encounter any issues when saving to a Model.bim file in Tabular Editor, and then subsequently opening from that file? Does the UI show the "ı" or "i" character?

**Comment by akurone** [comment]
yes, this is a century old interesting problem for us :). i agree with you that it is rooted in AMO (before openning an issue i checked the source couldn't find a related change).

for your questions:

- i did not change anything actually; just open model (from folder) and save (to folder) (folder or .bim doesn't matter, behaviour is same)

- i think the problem is related to casing of "i": in english capital form of "i" is "I". but in Turkish these are 2 different letters ("i" > "İ"; "ı">"I") . when string (or a word in pascalCase or CamelCase) starts with "I" (as in ImpersonationMode or Int64), and a case change occurs this is serialized as "i" (previous version serialized as "ı"). This also is the case for TMSL script generated. When i try to deploy i think server tries to change the case again and capitalizes "i" as "İ" and there we have a problem.. there is no problem with word "string" since the case of letter "i" in this word does not change.

- no issues on subsequent save/load operations in tabular editor.

i want to mention 2 points:
- tabular editor changes the encoding for files (current version)
- saved model.bim with tabular editor loaded it with VS; i could deploy (while TE could not due to this problem)

![untitled](https://user-images.githubusercontent.com/841676/41908631-517ade4a-794d-11e8-92fe-15e0520e2085.png)

**Comment by otykier** [comment]
Thanks for this clarification. Tabular Editor changing the encoding of the file is definitely a bug on my end, and not related to the AMO. I will make a fix that ensures that the encoding stays the same after a file is loaded and subsequently saved with Tabular Editor. In cases where the metadata is loaded from a server, I guess it should default to using UTF-8 without signature encoding. Hopefully that should solve the problem.

**Comment by otykier** [comment]
Does this issue still persist in the [latest version](https://github.com/otykier/TabularEditor/releases/tag/2.7.4), which is now targeting version 15.7 of the TOM?

**Comment by akurone** [comment]
with this version
![image](https://user-images.githubusercontent.com/841676/47870684-2cafc480-de1b-11e8-84c4-5281433c9b04.png)
I still get wrong "ı" in JSON values but VS does not warn me about encoding..
![image](https://user-images.githubusercontent.com/841676/47870628-11dd5000-de1b-11e8-9515-6abbe673c6c0.png)

**Comment by akurone** [comment]
hi, I have checked 2.8 release, this is still an issue in the release.
