### ISSUE TITLE
First Line break for the dax formatter

### ISSUE THREAD

**Issue by SteveFringe** [otykier/TabularEditor#638]
When I use the dax formatter in the tabular editor, it automatically deletes the first line break. 

So a measure with a variable definition in the beginning, which before looked like this (var definition on the new line)
![image](https://user-images.githubusercontent.com/72388338/95073950-fcab8300-070d-11eb-8e61-5018bed3ed47.png)

Starts looking like this:
![image](https://user-images.githubusercontent.com/72388338/95074005-14830700-070e-11eb-9935-19254112dc2a.png)

I'm not sure if it's only my taste, but to me it decreases the readability of the code. 

Is there a setting somewhere which allows to have a line break in the beginning of the measure?
Thanks in advance.

**Comment by marcosqlbi** [comment]
I am not sure this is a Tabular Editor issue - it is something we might have to modify in the DAX Formatter service. @otykier let me know if we want to discuss this by email.

**Comment by otykier** [comment]
@marcosqlbi I'm thinking an easy solution is to retain any line breaks at the start of the original expression. This is something I can easily add to TE after obtaining the formatted expression. Let me know if you see any issues with this approach. Thanks!

**Comment by marcosqlbi** [comment]
Probably it's better if you retain any line breaks at the start of the original expression using the current DAX Formatter API. I will probably implement a new API to format a DAX expression without the name of the measure at the beginning, also including multiple expressions in a single REST API. In that API I will preserve any initial line break, so moving to that API you could remove the control you can add now. I do not have a timeline yet, but it's unlikely to be ready before 2-3 weeks.

**Comment by otykier** [comment]
Fixed in [2.13.0](https://github.com/otykier/TabularEditor/releases/latest)

**Comment by dhoff01** [comment]
When I run the script "Selected.Measures.FormatDax();" to format the measures with the DAX  Formatter in the Advanced Scripting section it removes the 1st blank line and causes the formatting to get messed up.  Similar to the issue above that was fixed but apparently not for the scripting side because it is removing the blank line in the 1st row when running it by script.
![image](https://user-images.githubusercontent.com/76710304/103248507-754a6600-4930-11eb-866a-ea27fef0acc0.png)

**Comment by GollyJer** [comment]
I ran into this today and came up with this solution.
https://stackoverflow.com/q/74323111/25197

Hopefully it helps. 👍

**Comment by dkay-TCN** [comment]
I'm still experiencing this issue. Can't recall if it was always happening or if it started reoccurring but when I format a measure in TE2 using the script Model.AllMeasures.FormatDax(); it is removing the first line break.

However, if i use the DAX formatter button on a single measure it does not do this.
