### ISSUE TITLE
All measures in data model get duplicated when applying a Format String Expression to Calculation Group

### ISSUE THREAD

**Issue by MarkL76** [otykier/TabularEditor#831]
Hi,

We have a Power BI data model with 60+ tables.  We have added a simple Calculation Group containing 5 measures with different format types e.g. whole number and percentages, so that we can offer the users the ability to select which measure they want to review and it will be correctly formatted in the charts.

However we have found that when apply the Format String Expression, that every measure in our data model gets duplicated:

![image](https://user-images.githubusercontent.com/44395864/115262892-d8087d00-a12c-11eb-9c65-cefc660ecd98.png)

![image](https://user-images.githubusercontent.com/44395864/115262662-a68fb180-a12c-11eb-9951-d12517048b48.png)

![image](https://user-images.githubusercontent.com/44395864/115262564-92e44b00-a12c-11eb-80a4-684efea12fb3.png)

If we then clear the Format String Expression and save the changes all the duplicates disappear.

We have done similar on other models and have not seen this issue before.

We have downloaded the latest version of Tabular Editor and started our changes from afresh and the same issue occurred.

Tabular Editor version: [2.15.3]
Power BI Data model - latest April 2021 version.

Any thoughts appreciated!

Thanks

Mark

**Comment by jeffersonrand** [comment]
I can confirm same behavior.

**Comment by otykier** [comment]
I'm afraid this is a bug in Power BI Desktop (any tool that adds a calc group with dynamic format strings would probably cause the same effect). Will forward it to the team.

**Comment by marcosqlbi** [comment]
In reality, the additional measure is created to provide the dynamic format string. Such a measure exists in the model from a client's point of view, even though it should not be displayed at all. DAX Studio does a better job displaying them in a separate "Format String" folder:
![image](https://user-images.githubusercontent.com/13840816/115303836-6cda9d00-a164-11eb-91f7-1b075b849fe1.png)

Microsoft should fix this in Power BI Desktop...

**Comment by erapade** [comment]
In the latest release (2.92.706.0 April 2021) of PBI desktop it's even worse. Now they are spread around within the table, so you don't know witch is witch. Yes, you should choose the not-hidden one (if not both are hidden). 
![image](https://user-images.githubusercontent.com/17324892/115445068-acad8d00-a215-11eb-9157-93813105f83f.png)


Has anyone reported this to Microsoft, I don't want to create a duplicate, and I never get any votes ;-)

**Comment by otykier** [comment]
@erapade the team is already aware.

**Comment by otykier** [comment]
@erapade is this still an issue in the latest version of Power BI Desktop (May 2021)?

**Comment by erapade** [comment]
> @erapade is this still an issue in the latest version of Power BI Desktop (May 2021)?

@otykier Yes still an issue in latest version of PBI Desktop

**Comment by VAV11** [comment]
Still an issue in the latest version of PBI Desktop Version: 2.94.921.0 64-bit (June 2021).
@otykier said, that Microsoft is aware and working on a fix. Anyone knows where can I find information about the status of this fix?
Thank you all in advance.
Special thanks to @otykier for the gorgeous product.

**Comment by otykier** [comment]
You can help by letting Microsoft know that this is an important issue on the Power BI Community. Either by creating a new post or commenting on these existing threads:

- https://community.powerbi.com/t5/Desktop/A-duplicate-hidden-measure-created-when-creating-a-new-measure/m-p/1865688 (this one was marked as solved for some reason)
- https://community.powerbi.com/t5/Issues/Working-with-tabluar-editor-cause-creation-of-display-folders/idi-p/1243974

**Comment by rzhou12** [comment]
I am having the same problem. All measures have been duplicated and hidden, and I can't publish to Power BI with error message "The remote server returned an error:(400) Bad Request ". 

I am using the latest PBI Desktop Version: 2.99.782.0 64-bit (November 2021). All the duplicated measure gone when I cleared the formats from the grouped measures, but I couldn't publish until I cleared all group measures  in Tabular Editor.

Thank you in advance for your help!

![image](https://user-images.githubusercontent.com/45937142/143865799-bf83673c-6e73-4a7f-8e8c-b360652dbeec.png)

**Comment by yeykawb** [comment]
Did anyone else experience a recent update on this? Previously all measures got bundled up in their respective folder, "Format String Expressions", and was hidden away. All was fine until (I believe) the december update of PBI. Now they are grouped together with their respective measure, and hidden.
